### ISSUE TITLE
GoError string contains faulty URL

### ISSUE THREAD

**Issue by Pej0815** [grafana/k6#2537]
### Brief summary

The go error message for requests which tiemout contains a faulty URL.
The follwing characters will be rendered false
**%2F** -> **%!F(MISSING)**
**%2C** -> **%!C(MISSING)** 
**%3A** -> **%!A(MISSING)**

Copy&Past such an URL from the message into a browser can end up in different problems than expected.

K6 version 0.35 does not show this behaviour. 0.37 and 0.38 will show faulty URL. Not tested with 0.36.
Only GoError seems to be faulty. console.log and influxdb show correct URL.

### k6 version

37, 38

### OS

Windows 10, Ubuntu LTS 20.04

### Steps to reproduce the problem

Setup a test with request containing %2F, %2C and %3A in the query parameter
Let the server timeout this request

Behaviour is output of this script [test_Faulty.zip](https://github.com/grafana/k6/files/8689233/test_Faulty.zip)
Server way python with time.sleep(62).

Expected behaviour shows output of k6 0.35.0 run on windows 10
Actual behaviour shows output of k6 0.37.0 and 0.38.x

### Expected behaviour

ERRO[0060] Get "http://localhost:8080/Test?Image%2Fpng&%2C%3A": request timeout
        at go.k6.io/k6/js/common.Bind.func1 (native)
        at faultyString (file:///D:/GEO/UDP/Test/test_Faulty.js:46:53(5))  executor=ramping-vus scenario=A01 source=stacktrace

### Actual behaviour

ERRO[0060] GoError: Get "http://localhost:8080/Test?Image%!F(MISSING)png&%!C(MISSING)%!A(MISSING)": request timeout
        at go.k6.io/k6/js/modules/k6/http.(*RootModule).NewModuleInstance.func2 (native)
        at faultyString (file:///D:/GEO/UDP/Test/test_Faulty.js:30:4(5))
        at native  executor=ramping-vus scenario=A01 source=stacktrace

**Comment by mstoykov** [comment]
Hi, thank you for reporting this @Pej0815 :bow: 

This was introduced in v0.36.0, with https://github.com/grafana/k6/commit/3bcdabbf84b4232c69233ce67ec2d5adf8a4a57e. It seems like the previous way returning error was always using panics which ... isn't great IMO. But that was circumventing an [issue in the upstream JS VM  - goja](https://github.com/dop251/goja/issues/388). I have proposed a [fix](https://github.com/dop251/goja/pull/389), and hopefully it will be resolved by the next version.

I will keep this open until we update with that fix.
