### ISSUE TITLE
grpc.load is relative to the main module not the module it's called in

### ISSUE THREAD

**Issue by mstoykov** [grafana/k6#2781]
### Brief summary

`grpc.load` will open files not relative to the file it is being used in but relative to the file that was used in `k6 run file.js`.

### k6 version

v0.41.0

### OS

Linux

### Steps to reproduce the problem

1. clone k6 repo
2. add grpc_test.js with 
```javascript
import d from "./samples/grpc.js";
export default d;
```
3. k6.v0.41.0 run grpc_test.js

### Expected behaviour

We run the grpc samples test. 

### Actual behaviour

```
ERRO[0000] GoError: ./grpc_server/route_guide.proto: stat /home/mstoykov/work/k6io/k6/grpc_server/route_guide.proto: no such file or directory
        at reflect.methodValueCall (native)
        at file:///home/mstoykov/work/k6io/k6/samples/grpc.js:5:12(33)
        at go.k6.io/k6/js.(*InitContext).Require-fm (native)
        at file:///home/mstoykov/work/k6io/k6/grpc_test.js:1:0(13)
        at native  hint="script exception"
```

As you can clearly see it tries to open it relative to the main module

**Comment by mstoykov** [comment]
This in practice is bug in [InitEnv](https://github.com/grafana/k6/blob/5fa71b761185200d29c87eff16faa5e4a6c372b7/js/common/initenv.go) 

or even more accurately in the way it is constructed as it is single copy with the "root" directory of w/e the main module one is 
https://github.com/grafana/k6/blob/5fa71b761185200d29c87eff16faa5e4a6c372b7/js/bundle.go#L322-L327
