### ISSUE TITLE
setTimeout undefined in es5 library.

### ISSUE THREAD

**Issue by hrqiang** [grafana/k6#3329]
### Brief summary

Hi, I'm trying to use npm and webpack to call JsSip library with experimental WebSocket and timers.
I have in main.js
```
import { WebSocket } from "k6/experimental/websockets"
import { setTimeout } from "k6/experimental/timers"
import * as JsSIP from "jssip"
```
But when I call JsSIP, I got undefined for setTimeout. 

```
$ ./k6 run ./build/app.bundle.js
...
"error":"ReferenceError: setTimeout is not defined at value (webpack:///./node_modules/jssip/lib-es5/Transactions.js:95:15(14))"}  source=console
ERRO[0000] ReferenceError: setTimeout is not defined
running at value (webpack:///./node_modules/jssip/lib-es5/Transactions.js:95:15(14))
default at value (webpack:///./node_modules/jssip/lib-es5/RequestSender.js:91:29(86))
	at value (webpack:///./node_modules/jssip/lib-es5/Registrator.js:237:21(90))
	at k (webpack:///./node_modules/jssip/lib-es5/UA.js:981:0(27))
	at bound k (native)
	at value (webpack:///./node_modules/jssip/lib-es5/Transport.js:257:8(27))
	at bound value (native)
	at value (webpack:///./main.js:165:9(13))  executor=per-vu-iterations scenario=default source=stacktrace
```
Can you tell me why setTimeout is not available in library?
This is my webpack.config.js
```
var webpack = require('webpack');
var path = require('path');

module.exports = {
  mode: 'production',
  entry: './main.js',
  output: {
    path: path.resolve(__dirname, 'build'),
    libraryTarget: 'commonjs',
    filename: 'app.bundle.js',
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
      },
    ],
  },
  stats: {
    colors: true,
  },
  target: 'web',
  externals: /^(k6|https?\:\/\/)(\/.*)?/,
  devtool: 'source-map',
};
```

### k6 version

k6 v0.46.0 (2023-08-14T13:23:26+0000/v0.46.0-0-gcbd9e9ad, go1.20.7, darwin/amd64)

### OS

mac

### Steps to reproduce the problem

Hi, I'm trying to use npm and webpack to call JsSip library with experimental WebSocket and timers.
I have in main.js
```
import { WebSocket } from "k6/experimental/websockets"
import { setTimeout } from "k6/experimental/timers"
import * as JsSIP from "jssip"
```
But when I call JsSIP, I got undefined for setTimeout. 

```
$ ./k6 run ./build/app.bundle.js
...
"error":"ReferenceError: setTimeout is not defined at value (webpack:///./node_modules/jssip/lib-es5/Transactions.js:95:15(14))"}  source=console
ERRO[0000] ReferenceError: setTimeout is not defined
running at value (webpack:///./node_modules/jssip/lib-es5/Transactions.js:95:15(14))
default at value (webpack:///./node_modules/jssip/lib-es5/RequestSender.js:91:29(86))
	at value (webpack:///./node_modules/jssip/lib-es5/Registrator.js:237:21(90))
	at k (webpack:///./node_modules/jssip/lib-es5/UA.js:981:0(27))
	at bound k (native)
	at value (webpack:///./node_modules/jssip/lib-es5/Transport.js:257:8(27))
	at bound value (native)
	at value (webpack:///./main.js:165:9(13))  executor=per-vu-iterations scenario=default source=stacktrace
```
Can you tell me why setTimeout is not available in library?
This is my webpack.config.js
```
var webpack = require('webpack');
var path = require('path');

module.exports = {
  mode: 'production',
  entry: './main.js',
  output: {
    path: path.resolve(__dirname, 'build'),
    libraryTarget: 'commonjs',
    filename: 'app.bundle.js',
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
      },
    ],
  },
  stats: {
    colors: true,
  },
  target: 'web',
  externals: /^(k6|https?\:\/\/)(\/.*)?/,
  devtool: 'source-map',
};
```

### Expected behaviour

library use k6 setTimeout function.

### Actual behaviour

setTimeout undefined.

**Comment by codebien** [comment]
Hi @hrqiang,
`xk6/timers` module doesn't define a global setTimeout function as it is usually available in a browser. This specific feature is under evaluation and it is part of https://github.com/grafana/k6/issues/3297.
 
Subscribe to the issue to get the updates.

**Comment by mstoykov** [comment]
You can set `setTimeout` to `globalThis` as in

```javascript
import { setTimeout } from "k6/experimental/timers"
globalThis.setTimeout = setTimeout;
```
Probably better to do it for all four functions though.

Also it might be beneficial to do in a separate module from the main one, and import as the first things in the main module.


mainscript.js:
```javascript
import "./setGlobalTimeouts.js"
// the other parts of the imports

export const options = {} // your options

export default function() {
  // your code here
}
```

This way `setGlobalTimeouts.js` will have its code executed first and let you use `setTimeout` and co. as soon as possible.

Hope this helps you!
