### ISSUE TITLE
Implement `structuredClone()`

### ISSUE THREAD

**Issue by nicystalker** [grafana/k6#4083]
### Feature Description

Hello, I would like to use [`structuredClone()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/structuredClone) API in my test cases, currently it's not possible:

```bash
$ echo 'structuredClone({ hello: "" });' > test.js
$ k6 run test.js

         /\      Grafana   /‾‾/
    /\  /  \     |\  __   /  /
   /  \/    \    | |/ /  /   ‾‾\
  /          \   |   (  |  (‾)  |
 / __________ \  |_|\_\  \_____/

ERRO[0000] ReferenceError: structuredClone is not defined
        at file:///home/arch/k6-tests/test.js:1:43(5)  hint="script exception"

$ echo 'globalThis.structuredClone({ hello: "" });' > test.js
$ k6 run test.js

         /\      Grafana   /‾‾/
    /\  /  \     |\  __   /  /
   /  \/    \    | |/ /  /   ‾‾\
  /          \   |   (  |  (‾)  |
 / __________ \  |_|\_\  \_____/

ERRO[0000] TypeError: Object has no member 'structuredClone'
        at file:///home/arch/k6-tests/test.js:1:54(6)  hint="script exception"

```

I'm guessing it's not implemented in current k6 version?

```
❯ k6 --version
k6 v0.55.0 (commit/a9ef6638f1, go1.23.2, linux/amd64)
```

**Comment by olegbespalov** [comment]
That's correct, neither `k6` nor `sobek` have no support of the `[structuredClone](https://developer.mozilla.org/en-US/docs/Web/API/Window/structuredClone)` right now 😢
