### ISSUE TITLE
Various Panics using stable k6/browser

### ISSUE THREAD

**Issue by adamgrant-engageli** [grafana/k6#4085]
### Brief summary

k6-browser is throwing various non-repeating errors using the non-experimental k6/browser usually seen within calls to page.evaluate

### k6 version

0.55.0

### OS

macOS 15.1.1

### Docker version and image (if applicable)

docker.desktop 4.35.1 (173168)

### Steps to reproduce the problem

Here is an excerpt of our sendSocketChatMsg function that works as expected with the k6/experimental/browser but inevitably panics in different ways within the evaluated callback when using the stable k6/browser. I will post some of the panics I am seeing in the Actual Behavior section
```js
export const generateUUID = () => {
    // UUIDv4 pattern: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx
    return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, function (c) {
        const r = (Math.random() * 16) | 0,
            v = c == "x" ? r : (r & 0x3) | 0x8;
        return v.toString(16);
    });
};

const isSpecialChatDestination = (msgTo: string) => {
    return Object.values(DISPLAY_NAMES).includes(msgTo as DISPLAY_NAMES);
};

export const sendSocketChatMsg = async (page: Page, robotName: string, msg?: string, msgTo?: string) => {
    try {
        const id = generateUUID();
        let specialDestination;
        if (!msgTo) {
            // eslint-disable-next-line no-param-reassign
            msgTo = DISPLAY_NAMES.ROOM as string;
            specialDestination = true;
        } else if (msgTo === "Staff") {
            // eslint-disable-next-line no-param-reassign
            msgTo = DISPLAY_NAMES.STAFF_IN_ROOM as string;
            specialDestination = true;
        } else if (msgTo === "Room") {
            // eslint-disable-next-line no-param-reassign
            msgTo = DISPLAY_NAMES.ROOM as string;
            specialDestination = true;
        } else {
            // check for special destination:
            specialDestination = isSpecialChatDestination(msgTo);
        }
        console.log(`${new Date().toISOString()} ${robotName} %%%% call page.evaluate for chat`, {
            robotName,
            msg,
            msgTo,
            id,
            specialDestination,
        });
        await page.evaluate(
            (data) => {
                let userName: string;
                try {
                    const studentSocketConnectionInstance = window.redactedConnection.getInstance();
                    if (!studentSocketConnectionInstance) {
                        return { rc: -1, err: "No socket found" };
                    }
                    const studentState = window.globalStudentState;
                    let name;
                    if (data.specialDestination) {
                        // room, staff etc, no lookup needed
                        userName = data.msgTo;
                        name = data.msgTo;
                    } else {
                        const targetUser = studentState.participants.find((x: any) => x.name.startsWith(data.msgTo));
                        userName = targetUser?.userName;
                        name = targetUser?.name;
                    }
                    const message =
                        data.msg && userName
                            ? data.msg
                            : !userName
                              ? `FAILED TO FIND RECIPIENT: ${data.msgTo} for msg (${data.msg})`
                              : "No message text found";
                    studentSocketConnectionInstance
                        .sendChatMessage({
                            id: data.id,
                            text: message,
                            when: new Date().toISOString(),
                            // email
                            targetUser: userName || "STAFF_IN_ROOM",
                            roomId: studentState.roomId,
                            vtgId: studentState.vtgId,
                            // display name
                            targetName: name || "STAFF_IN_ROOM",
                            authorUserName: studentState.username,
                            authorDisplayName: studentState.displayName,
                            targetRoomId: studentState.roomId,
                            shouldNotify: false,
                        })
                        .then((res: any) => console.log("Send Chat res:", res))
                        .catch((err: Error) =>
                            console.log(
                                "ERROR sendChatMsg robot",
                                { robotName: data.robotName, userName },
                                err,
                                err.toString(),
                            ),
                        )
                        .finally(() => null);
                    console.log(data.robotName, "CHAT from socket done");
                    return 0;
                } catch (err) {
                    console.log("ERROR: robot chat msg send", data, err);
                    return { rc: -1, err };
                }
            },
            { robotName, msg, msgTo, id, specialDestination },
        );
        console.log(`${new Date().toISOString()} ${robotName} %%%% call page.evaluate for chat: DONE`);
        return 0;
    } catch (err) {
        console.error(
            `${new Date().toISOString()} ${robotName} ERROR sendSocketChatMsg`,
            err,
            (err as Error).toString(),
            { msg, msgTo },
        );
        return { rc: -1, err };
    }
};
```

### Expected behaviour

This works as expected with the old k6/experimental/browser the call to studentSocketConnectionInstance.sendChatMessage is successful.

### Actual behaviour
```
panic: TypeError: Object has no member 'call' at call (native)
running (01m01.7s), 3/3 VUs, 0 complete and 0 interrupted iterations
goroutine 4204 [running]:--------------------------------] 3 VUs  01m01.7s/26m40s  0/3 iters, 1 per VU
github.com/grafana/sobek.(baseJsFuncObject)._call(...)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/func.go:444
github.com/grafana/sobek.(baseJsFuncObject).call(0x0?, {{0x106612518, 0x14001557980}, {0x0, 0x0, 0x0}}, {0x0?, 0x0?})
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/func.go:450 +0x94
github.com/grafana/sobek.(baseJsFuncObject).Call(...)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/func.go:382
github.com/grafana/sobek.(Object).tryPrimitive(0x14001557980, {0x105dcbfc9?, 0x0?})
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/object.go:842 +0xac
github.com/grafana/sobek.(Object).ordinaryToPrimitiveString(0x14001557980)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/object.go:866 +0x2c
github.com/grafana/sobek.(Object).toPrimitiveString(0x14001557980)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/object.go:905 +0x48
github.com/grafana/sobek.(*Object).String(0x0?)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/value.go:715 +0x1c
github.com/grafana/xk6-browser/browser.mapPage.func11.1()
        github.com/grafana/xk6-browser@v1.9.1/browser/page_mapping.go:85 +0x44
github.com/grafana/xk6-browser/k6ext.promise.func1()
        github.com/grafana/xk6-browser@v1.9.1/k6ext/promise.go:24 +0x38
created by github.com/grafana/xk6-browser/k6ext.promise in goroutine 102
        github.com/grafana/xk6-browser@v1.9.1/k6ext/promise.go:23 +0x98
```

--------------------------
```
panic: runtime error: slice bounds out of range [20:0] [recovered]
running panic: runtime error: slice bounds out of range [20:0]ations
perVuIterations   [--------------------------------------] 1 VUs  01m21.9s/26m40s  0/1 iters, 1 per VU
goroutine 104 [running]:
github.com/grafana/sobek.(Runtime).runWrapped.func1()
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/runtime.go:2504 +0xf4
panic({0x102282300?, 0x140001d0db0?})
        runtime/panic.go:785 +0x124
github.com/grafana/sobek.(vm).clearStack(0x14000b52a20)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/vm.go:3727 +0xb4
github.com/grafana/sobek.(Runtime).runWrapped(0x140011c6c08, 0x14000101008?)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/runtime.go:2515 +0x90
github.com/grafana/sobek.AssertFunction.func1({0x0?, 0x0?}, {0x140015bd030?, 0x0?, 0x0?})
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/runtime.go:2463 +0x78
github.com/grafana/sobek.(Runtime).wrapPromiseReaction.func1({0x1020f0c80?, 0x14000623ce0?})
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/builtin_promise.go:602 +0xa8
go.k6.io/k6/js/promises.New.func2.1()
        go.k6.io/k6@v0.55.0/js/promises/promises.go:43 +0x2c
go.k6.io/k6/js/eventloop.(EventLoop).Start(0x140008a5c20, 0x14000c90300)
        go.k6.io/k6@v0.55.0/js/eventloop/eventloop.go:177 +0x160
go.k6.io/k6/js.(VU).runFn(0x14001397900, {0x1023aeb68, 0x14000dd14f0}, 0x1, 0x140015543d8, 0x140014e9d90, {0x1400123a280, 0x1, 0x1})
        go.k6.io/k6@v0.55.0/js/runner.go:840 +0x1f4
go.k6.io/k6/js.(*ActiveVU).RunOnce(0x14000f4dbc0)
        go.k6.io/k6@v0.55.0/js/runner.go:773 +0x3d0
go.k6.io/k6/lib/executor.PerVUIterations.Run.getIterationRunner.func7({0x1023aeb30, 0x1400155a360}, {0x102397fa0?, 0x14000f4dbc0?})
        go.k6.io/k6@v0.55.0/lib/executor/helpers.go:108 +0x44
go.k6.io/k6/lib/executor.PerVUIterations.Run.func5({0x1023a5ee8, 0x14001397900})
        go.k6.io/k6@v0.55.0/lib/executor/per_vu_iterations.go:228 +0x318
created by go.k6.io/k6/lib/executor.PerVUIterations.Run in goroutine 102
        go.k6.io/k6@v0.55.0/lib/executor/per_vu_iterations.go:241 +0x89c
```
----------------------
```
panic: TypeError: Method WeakMap.prototype.get called on incompatible receiver [object Object] at get (native)
running (00m40.2s), 3/3 VUs, 0 complete and 0 interrupted iterations
goroutine 3528 [running]:--------------------------------] 3 VUs  00m40.2s/26m40s  0/3 iters, 1 per VU
github.com/grafana/sobek.(baseJsFuncObject)._call(...)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/func.go:444
github.com/grafana/sobek.(baseJsFuncObject).call(0x0?, {{0x10264e688, 0x14001a91c20}, {0x0, 0x0, 0x0}}, {0x0?, 0x0?})
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/func.go:450 +0x94
github.com/grafana/sobek.(baseJsFuncObject).Call(...)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/func.go:382
github.com/grafana/sobek.(Object).tryPrimitive(0x14001a91c20, {0x101e07b99?, 0x527261656c632e66?})
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/object.go:842 +0xac
github.com/grafana/sobek.(Object).ordinaryToPrimitiveString(0x14001a91c20)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/object.go:866 +0x2c
github.com/grafana/sobek.(Object).toPrimitiveString(0x14001a91c20)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/object.go:905 +0x48
github.com/grafana/sobek.(*Object).String(0x766e61632c7d752c?)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/value.go:715 +0x1c
github.com/grafana/xk6-browser/browser.mapPage.func11.1()
        github.com/grafana/xk6-browser@v1.9.1/browser/page_mapping.go:85 +0x44
github.com/grafana/xk6-browser/k6ext.promise.func1()
        github.com/grafana/xk6-browser@v1.9.1/k6ext/promise.go:24 +0x38
created by github.com/grafana/xk6-browser/k6ext.promise in goroutine 115
        github.com/grafana/xk6-browser@v1.9.1/k6ext/promise.go:23 +0x98
```
-----------------------
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
running panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x104d9cbc4]s/26m40s  0/3 iters, 1 per VU
goroutine 4536 [running]:
github.com/grafana/sobek.(vm).handleThrow(0x14000bf6000, {0x1062531a0, 0x107548920})
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/vm.go:840 +0x3c4
github.com/grafana/sobek.(vm).runTryInner.func1()
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/vm.go:882 +0x48
panic({0x1062531a0?, 0x107548920?})
        runtime/panic.go:785 +0x124
github.com/grafana/sobek.(vm).run(0x14000bf6000)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/vm.go:632 +0xc4
github.com/grafana/sobek.(vm).runTryInner(0x14000bf6000?)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/vm.go:886 +0x50
github.com/grafana/sobek.(baseJsFuncObject).__call(0x1400199d740, {0x0?, 0x0, 0x1077a45b8?}, {0x0, 0x0}, {0x10653db38?, 0x1400149e000?})
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/func.go:426 +0x5cc
github.com/grafana/sobek.(baseJsFuncObject)._call(...)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/func.go:442
github.com/grafana/sobek.(baseJsFuncObject).call(0x0?, {{0x10653db38, 0x1400149e000}, {0x0, 0x0, 0x0}}, {0x0?, 0x0?})
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/func.go:450 +0x74
github.com/grafana/sobek.(baseJsFuncObject).Call(...)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/func.go:382
github.com/grafana/sobek.(Object).tryPrimitive(0x1400149e000, {0x105cf9102?, 0x53223a22706f502d?})
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/object.go:842 +0xac
github.com/grafana/sobek.(Object).ordinaryToPrimitiveString(0x1400149e000)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/object.go:866 +0x2c
github.com/grafana/sobek.(Object).toPrimitiveString(0x1400149e000)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/object.go:905 +0x48
github.com/grafana/sobek.(Object).String(0x5c65646172677075?)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/value.go:715 +0x1c
github.com/grafana/xk6-browser/browser.mapPage.func11.1()
        github.com/grafana/xk6-browser@v1.9.1/browser/page_mapping.go:85 +0x44
github.com/grafana/xk6-browser/k6ext.promise.func1()
        github.com/grafana/xk6-browser@v1.9.1/k6ext/promise.go:24 +0x38
created by github.com/grafana/xk6-browser/k6ext.promise in goroutine 91
        github.com/grafana/xk6-browser@v1.9.1/k6ext/promise.go:23 +0x98
```
--------------------------
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
running panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x100d29724]s/26m40s  0/3 iters, 1 per VU
goroutine 4647 [running]:
github.com/grafana/sobek.(vm).handleThrow(0x1400120c000, {0x101b381c0, 0x102d72fe0})
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/vm.go:840 +0x3c4
github.com/grafana/sobek.(vm).runTryInner.func1()
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/vm.go:882 +0x48
panic({0x101b381c0?, 0x102d72fe0?})
        runtime/panic.go:785 +0x124
github.com/grafana/sobek.(vm).run(0x1400120c000)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/vm.go:632 +0xc4
github.com/grafana/sobek.(vm).runTryInner(0x1400120c000?)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/vm.go:886 +0x50
github.com/grafana/sobek.(baseJsFuncObject).__call(0x14000ed4d80, {0x0?, 0x0, 0x102f9ca68?}, {0x0, 0x0}, {0x101e0db38?, 0x140026baf30?})
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/func.go:426 +0x5cc
github.com/grafana/sobek.(baseJsFuncObject)._call(...)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/func.go:442
github.com/grafana/sobek.(baseJsFuncObject).call(0x0?, {{0x101e0db38, 0x140026baf30}, {0x0, 0x0, 0x0}}, {0x0?, 0x0?})
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/func.go:450 +0x74
github.com/grafana/sobek.(baseJsFuncObject).Call(...)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/func.go:382
github.com/grafana/sobek.(Object).tryPrimitive(0x140026baf30, {0x101625a75?, 0x0?})
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/object.go:842 +0xac
github.com/grafana/sobek.(Object).ordinaryToPrimitiveString(0x140026baf30)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/object.go:866 +0x2c
github.com/grafana/sobek.(Object).toPrimitiveString(0x140026baf30)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/object.go:905 +0x48
github.com/grafana/sobek.(Object).String(0x0?)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/value.go:715 +0x1c
github.com/grafana/xk6-browser/browser.mapPage.func11.1()
        github.com/grafana/xk6-browser@v1.9.1/browser/page_mapping.go:85 +0x44
github.com/grafana/xk6-browser/k6ext.promise.func1()
        github.com/grafana/xk6-browser@v1.9.1/k6ext/promise.go:24 +0x38
created by github.com/grafana/xk6-browser/k6ext.promise in goroutine 132
        github.com/grafana/xk6-browser@v1.9.1/k6ext/promise.go:23 +0x98
```
--------------------------------
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
running panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x104b81724]s/26m40s  0/3 iters, 1 per VU
goroutine 4134 [running]:
github.com/grafana/sobek.(vm).handleThrow(0x14000d7b680, {0x1059901c0, 0x106bcafe0})
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/vm.go:840 +0x3c4
github.com/grafana/sobek.(vm).runTryInner.func1()
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/vm.go:882 +0x48
panic({0x1059901c0?, 0x106bcafe0?})
        runtime/panic.go:785 +0x124
github.com/grafana/sobek.(vm).run(0x14000d7b680)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/vm.go:632 +0xc4
github.com/grafana/sobek.(vm).runTryInner(0x14000d7b680?)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/vm.go:886 +0x50
github.com/grafana/sobek.(baseJsFuncObject).__call(0x14001687d40, {0x0?, 0x0, 0x106df4108?}, {0x0, 0x0}, {0x105c65b38?, 0x140017bf3b0?})
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/func.go:426 +0x5cc
github.com/grafana/sobek.(baseJsFuncObject)._call(...)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/func.go:442
github.com/grafana/sobek.(baseJsFuncObject).call(0x0?, {{0x105c65b38, 0x140017bf3b0}, {0x0, 0x0, 0x0}}, {0x0?, 0x0?})
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/func.go:450 +0x74
github.com/grafana/sobek.(baseJsFuncObject).Call(...)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/func.go:382
github.com/grafana/sobek.(Object).tryPrimitive(0x140017bf3b0, {0x10547da75?, 0x0?})
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/object.go:842 +0xac
github.com/grafana/sobek.(Object).ordinaryToPrimitiveString(0x140017bf3b0)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/object.go:866 +0x2c
github.com/grafana/sobek.(Object).toPrimitiveString(0x140017bf3b0)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/object.go:905 +0x48
github.com/grafana/sobek.(Object).String(0x0?)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/value.go:715 +0x1c
github.com/grafana/xk6-browser/browser.mapPage.func11.1()
        github.com/grafana/xk6-browser@v1.9.1/browser/page_mapping.go:85 +0x44
github.com/grafana/xk6-browser/k6ext.promise.func1()
        github.com/grafana/xk6-browser@v1.9.1/k6ext/promise.go:24 +0x38
created by github.com/grafana/xk6-browser/k6ext.promise in goroutine 116
        github.com/grafana/xk6-browser@v1.9.1/k6ext/promise.go:23 +0x98
```
-------------------------------------
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
running panic: runtime error: invalid memory address or nil pointer dereference [recovered]
perVuItepanic: runtime error: invalid memory address or nil pointer dereference [recovered]s, 1 per VU
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x105429724]

goroutine 40 [running]:
github.com/grafana/sobek.(*Runtime).runWrapped.func1()
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/runtime.go:2504 +0xf4
panic({0x1062381c0?, 0x107472fe0?})
        runtime/panic.go:785 +0x124
github.com/grafana/sobek.(*vm).handleThrow(0x140005bafc0, {0x1062381c0, 0x107472fe0})
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/vm.go:840 +0x3c4
github.com/grafana/sobek.(*vm).try.func1()
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/vm.go:859 +0x48
panic({0x1062381c0?, 0x107472fe0?})
        runtime/panic.go:785 +0x124
github.com/grafana/sobek.(*vm).handleThrow(0x140005bafc0, {0x1062381c0, 0x107472fe0})
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/vm.go:840 +0x3c4
github.com/grafana/sobek.(*vm).runTryInner.func1()
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/vm.go:882 +0x48
panic({0x1062381c0?, 0x107472fe0?})
        runtime/panic.go:785 +0x124
github.com/grafana/sobek.(*vm).run(0x140005bafc0)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/vm.go:632 +0xc4
github.com/grafana/sobek.(*vm).runTryInner(0x140005bafc0?)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/vm.go:886 +0x50
github.com/grafana/sobek.(*baseJsFuncObject).__call(0x1400175a9c0, {0x14001d3e2c0?, 0x1, 0x1400103f1c0?}, {0x0, 0x0}, {0x10650e128?, 0x1074dfb20?})
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/func.go:426 +0x5cc
github.com/grafana/sobek.(*baseJsFuncObject)._call(...)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/func.go:442
github.com/grafana/sobek.(*baseJsFuncObject).call(0x14001ef75b8?, {{0x10650e128, 0x1074dfb20}, {0x14001d3e2c0, 0x1, 0x1}}, {0x0?, 0x0?})
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/func.go:450 +0x74
github.com/grafana/sobek.(*baseJsFuncObject).Call(...)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/func.go:382
github.com/grafana/sobek.(*Runtime).callJobCallback(0x14001833350?, 0x104acea4c?, {0x10650e128?, 0x1074dfb20?}, {0x14001d3e2c0?, 0x70?, 0x14001ef7658?})
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/runtime.go:2940 +0x58
github.com/grafana/sobek.(*Promise).fulfill.(*Runtime).triggerPromiseReactions.(*Runtime).newPromiseReactionJob.func1.1()
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/builtin_promise.go:214 +0xac
github.com/grafana/sobek.(*vm).try(0x140005bafc0, 0x14001ef77b0)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/vm.go:863 +0x1d8
github.com/grafana/sobek.(*Promise).fulfill.(*Runtime).triggerPromiseReactions.(*Runtime).newPromiseReactionJob.func1()
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/builtin_promise.go:213 +0xc0
github.com/grafana/sobek.(*Runtime).leave(0x14000a2ac08)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/runtime.go:2813 +0xe0
github.com/grafana/sobek.(*Runtime).runWrapped(0x14000a2ac08, 0x1400101a008?)
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/runtime.go:2513 +0x84
github.com/grafana/sobek.AssertFunction.func1({0x0?, 0x0?}, {0x14001d3e2b0?, 0x0?, 0x0?})
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/runtime.go:2463 +0x78
github.com/grafana/sobek.(*Runtime).wrapPromiseReaction.func1({0x10621c1a0?, 0x140018332f0?})
        github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/builtin_promise.go:602 +0xa8
go.k6.io/k6/js/promises.New.func1.1()
        go.k6.io/k6/js/promises/promises.go:37 +0x2c
go.k6.io/k6/js/eventloop.(*EventLoop).Start(0x1400119cdc0, 0x140010ed860)
        go.k6.io/k6/js/eventloop/eventloop.go:177 +0x160
go.k6.io/k6/js.(*VU).runFn(0x1400150f900, {0x1064f9f48, 0x14001112f00}, 0x1, 0x14001288558, 0x14000f78640, {0x14000b65cb0, 0x1, 0x1})
        go.k6.io/k6/js/runner.go:840 +0x1f4
go.k6.io/k6/js.(*ActiveVU).RunOnce(0x1400067f040)
        go.k6.io/k6/js/runner.go:773 +0x3d0
go.k6.io/k6/lib/executor.PerVUIterations.Run.getIterationRunner.func7({0x1064f9f10, 0x1400120fb30}, {0x1064e3820?, 0x1400067f040?})
        go.k6.io/k6/lib/executor/helpers.go:108 +0x44
go.k6.io/k6/lib/executor.PerVUIterations.Run.func5({0x1064f15e8, 0x1400150f900})
        go.k6.io/k6/lib/executor/per_vu_iterations.go:228 +0x318
created by go.k6.io/k6/lib/executor.PerVUIterations.Run in goroutine 36
        go.k6.io/k6/lib/executor/per_vu_iterations.go:241 +0x89c
```

**Comment by ankur22** [comment]
Hi @adamgrant-engageli,

Any chance you could send us a full test script that exhibits this issue when working with `k6/browser` vs `k6/experimental/browser`? I can't see anything obvious that could cause any issues or replicate the issue with the excerpt you have given us. Also, what version of k6 are you running?

**Comment by adamgrant-engageli** [comment]
k6 version 0.55.0
I will try to get permission to share the test library sources.

**Comment by max-tremblay** [comment]
Hi,

I couldn't create a simple test case to reproduce the issue, but I believe I have identified where it occurs:

In `js/modules/k6/browser/k6ext/promise.go`, you have this code:

```go
func promise(ctx context.Context, fn PromisifiedFunc) *sobek.Promise {
	p, resolve, reject := promises.New(GetVU(ctx))
	go func() {
		v, err := fn()
		if err != nil {
			reject(err)
			return
		}
		resolve(v)
	}()

	return p
}
```

There is a race condition where the parent goroutine and its child share the same `Runtime` object, allowing both to access the internal VM object concurrently. Since both are modifying the stack simultaneously, this leads to index/pointer issues.

Attached file is an example from one of my run with the `-race` flag being used

[panic.txt](https://github.com/user-attachments/files/18526161/panic.txt)

**Comment by max-tremblay** [comment]
Hi @mstoykov,

Looks like it's working. Using v0.56.0 tag I was able to get a panic message under 3m systematically, but using the latest commit it is now stable since 20m and I don't have any goroutine race messages as well. Great work!

Thanks a lot!

**Comment by adamgrant-engageli** [comment]
Very good! thank you for the fix @mstoykov
