### ISSUE TITLE
Panic (NPD) `ElementHandle.boundingBox`

### ISSUE THREAD

**Issue by olegbespalov** [grafana/k6#4112]
### Brief summary

We're getting nil from chrome [here](https://github.com/grafana/xk6-browser/blob/4b09c5ff01f2cd0e87d7590b361cac691a75c962/common/element_handle.go#L48), which is likely because the element no longer exists. We should compare our implementation with how PW works out hit targets when working with the tap API.

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x157836e]

goroutine 28823895 [running]:
github.com/grafana/xk6-browser/common.(*ElementHandle).boundingBox(0xc017adafa0)
github.com/grafana/xk6-browser@v1.9.2-0.20241118153201-d741e4540a3a/common/element_handle.go:52 +0x12e
github.com/grafana/xk6-browser/common.(*ElementHandle).checkHitTargetAt(0xc028915d60, {0x1f9ad78?, 0xc027a3ae70?}, {0x4082e55000000000, 0x407ac60000000000})
github.com/grafana/xk6-browser@v1.9.2-0.20241118153201-d741e4540a3a/common/element_handle.go:76 +0x8e
github.com/grafana/xk6-browser/common.(*ElementHandle).newPointerAction.func1({0x1f9ad78, 0xc027a3ae70}, 0x0?)
github.com/grafana/xk6-browser@v1.9.2-0.20241118153201-d741e4540a3a/common/element_handle.go:1627 +0x517
github.com/grafana/xk6-browser/common.retryPointerAction({0x1f9ad78, 0xc027a3ae70}, 0xc0bd0755a0, 0xc0af58b500)
github.com/grafana/xk6-browser@v1.9.2-0.20241118153201-d741e4540a3a/common/element_handle.go:1672 +0x3c
github.com/grafana/xk6-browser/common.(*ElementHandle).newPointerAction.func2({0x1f9ad78, 0xc027a3ae70}, 0xc083de1650, 0xc083de16c0)
github.com/grafana/xk6-browser@v1.9.2-0.20241118153201-d741e4540a3a/common/element_handle.go:1654 +0x59
github.com/grafana/xk6-browser/common.(*Frame).click.(*Frame).newPointerAction.func2({0x1f9ad78, 0xc027a3ae70}, 0xc083de1650, 0xc083de16c0)
github.com/grafana/xk6-browser@v1.9.2-0.20241118153201-d741e4540a3a/common/frame.go:2208 +0x116
created by github.com/grafana/xk6-browser/common.call in goroutine 28823883
github.com/grafana/xk6-browser@v1.9.2-0.20241118153201-d741e4540a3a/common/helpers.go:103 +0x14c
```

Test run id: 3556475

### xk6-browser version

v1.9.2

### OS

NA

### Chrome version

NA

### Steps to reproduce the problem

-

### Expected behaviour

No panic

### Actual behaviour

Panic

**Comment by mstoykov** [comment]
Fixed by https://github.com/grafana/k6/pull/5163
