### ISSUE TITLE
Nil pointer dereference in session.Execute

### ISSUE THREAD

**Issue by ankur22** [grafana/k6#4121]
### Brief summary

Nil pointer dereference.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x12487a2]

goroutine 430051 [running]:
github.com/grafana/xk6-browser/common.(*Session).Execute(0x0, {0x1b58040, 0xc0026fb320}, {0x17a4c16, 0xa}, {0x0?, 0x0}, {0x0, 0x0})
	github.com/grafana/xk6-browser@v1.3.0/common/session.go:111 +0x82
github.com/chromedp/cdproto/cdp.Execute({0x1b58040, 0xc0026fb320}, {0x17a4c16, 0xa}, {0x0, 0x0}, {0x0, 0x0})
	github.com/chromedp/cdproto@v0.0.0-20221023212508-67ada9507fb2/cdp/types.go:48 +0xbb
github.com/chromedp/cdproto/log.(*EnableParams).Do(0x1b58078?, {0x1b58040?, 0xc0026fb320?})
	github.com/chromedp/cdproto@v0.0.0-20221023212508-67ada9507fb2/log/log.go:63 +0x3a
github.com/grafana/xk6-browser/common.(*Worker).initEvents(0xc0010e3b00)
	github.com/grafana/xk6-browser@v1.3.0/common/worker.go:54 +0x15d
github.com/grafana/xk6-browser/common.NewWorker({0x1b58078, 0xc002b405a0}, {0x1b5f158, 0x0}, {0xc00016afc0, 0x20}, {0xc0013b2d80, 0x76})
	github.com/grafana/xk6-browser@v1.3.0/common/worker.go:36 +0x21d
github.com/grafana/xk6-browser/common.(*FrameSession).attachWorkerToTarget(0xc001fdd680, 0xc001e5c990, {0xc00016af00, 0x20})
	github.com/grafana/xk6-browser@v1.3.0/common/frame_session.go:988 +0xa5
github.com/grafana/xk6-browser/common.(*FrameSession).onAttachedToTarget(0xc001fdd680, 0xc00223dae0)
	github.com/grafana/xk6-browser@v1.3.0/common/frame_session.go:907 +0x2a5
github.com/grafana/xk6-browser/common.(*FrameSession).initEvents.func1()
	github.com/grafana/xk6-browser@v1.3.0/common/frame_session.go:282 +0x368
created by github.com/grafana/xk6-browser/common.(*FrameSession).initEvents in goroutine 430026
	github.com/grafana/xk6-browser@v1.3.0/common/frame_session.go:223 +0x19b
'
```

With test id: 2292256

### xk6-browser version

v1.3.0 (browser) v0.48.0 (k6)

### OS

NA

### Chrome version

NA

### Steps to reproduce the problem

Go to test 2292256

### Expected behaviour

Should not panic.

### Actual behaviour

Panics.

**Comment by ankur22** [comment]
I'm closing this as there's not enough information on how this happened and i've not seen this recently.
