### ISSUE TITLE
ElementHandle: nil pointer dereference

### ISSUE THREAD

**Issue by lthurr** [grafana/k6#4123]
### Brief summary

Hi, I have been trying to set a pipeline to automatically run our k6 browser tests in order to collect periodically some web vital metrics.

The problem is that I can't manage to make it work because I'm getting `panic: runtime error: invalid memory address or nil pointer dereference`.  I have been trying to look out for solutions or even if this was reported before and I haven't found anything. So I'm kindly requesting your support here.

The k6 version run within the jenkins job returns
```
k6 v0.46.0 (2023-08-14T13:23:26+0000/v0.46.0-0-gcbd9e9ad, go1.20.7, linux/amd64)
```

let me proceed to explain what I see

### k6 version

k6 v0.46.0 (2023-08-14T13:23:26+0000/v0.46.0-0-gcbd9e9ad, go1.20.7, linux/amd64)

### OS

linux

### Steps to reproduce the problem

I have two examples, 
one of them triggers the `panic: runtime error`. However, when I execute the example script described in k6.io, this one works perfectly fine.

### The following script triggers the panic

```
import { browser } from 'k6/experimental/browser';
import { check } from 'k6';


export let options = {
  scenarios: {
    addProductToCart: {
      executor: 'shared-iterations',
      iterations: 10,
      vus: 1,
      options: {
        browser: {
          type: 'chromium',
        },
      },
    },
  }
};

export default async function () {
    const context = browser.newContext();
    try {
      context.addCookies([{name: COOKIE_NAME, value: COOKIE_VALUE, domain: COOKIE_DOMAIN, path: "/"}]);
      const page = context.newPage();

      await page.goto(url, { waitUntil: 'networkidle' });

      await page.locator(loc1).click();
      await page.locator(loc2).click();
      await page.locator(loc3).click();
      page.locator(loc4).waitFor({ state: 'visible' });


      check(page, {
          'Item is added to cart': page.locator(loc5).textContent() == 'validation text'
        }
      );
    } finally {
      page.close();
    }
}

```

### The following script doesn't trigger the panic

```
import { browser } from 'k6/experimental/browser';


export let options = {
  scenarios: {
    example: {
      executor: 'shared-iterations',
      iterations: 10,
      vus: 1,
      options: {
        browser: {
          type: 'chromium',
        },
      },
    },
  }
};

export default async function () {
  const page = browser.newPage();

  try {
    await page.goto('https://test.k6.io/');
  } finally {
    page.close();
  }
}
```

### Expected behaviour

Script is executed succesfully

### Actual behaviour

When I execute the file provided above, I face the following output

```
panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1195471]

goroutine 1000 [running]:
github.com/grafana/xk6-browser/common.(*ElementHandle).clickablePoint(0xc00068d9f0)
	github.com/grafana/xk6-browser@v1.0.2/common/element_handle.go:181 +0x2d1
github.com/grafana/xk6-browser/common.(*ElementHandle).newPointerAction.func1({0x1a09cb0, 0xc000ae8ae0}, 0x0?)
	github.com/grafana/xk6-browser@v1.0.2/common/element_handle.go:1441 +0x3ba
github.com/grafana/xk6-browser/common.retryPointerAction({0x1a09cb0, 0xc000ae8ae0}, 0xc001f78b80, 0xc0023d6240)
	github.com/grafana/xk6-browser@v1.0.2/common/element_handle.go:1488 +0x42
github.com/grafana/xk6-browser/common.(*ElementHandle).newPointerAction.func2({0x1a09cb0?, 0xc000ae8ae0?}, 0xc0023d6240?, 0x0?)
	github.com/grafana/xk6-browser@v1.0.2/common/element_handle.go:1476 +0x3b
github.com/grafana/xk6-browser/common.(*Frame).newPointerAction.func1({0x1a09cb0, 0xc000ae8ae0}, 0xc0007f2ea0, 0xc0007f2f00)
	github.com/grafana/xk6-browser@v1.0.2/common/frame.go:1989 +0x169
created by github.com/grafana/xk6-browser/common.call
	github.com/grafana/xk6-browser@v1.0.2/common/helpers.go:102 +0x17b
script returned exit code 2
```

**Comment by yevk** [comment]
@olegbespalov, this looks related to https://github.com/grafana/xk6-browser/issues/1502#issuecomment-2535841917, as @ankur22 mentioned in https://github.com/grafana/xk6-browser/issues/1502#issuecomment-2451867303.

Any chance this can be fixed the same way you fixed the screenshotter?

**Comment by olegbespalov** [comment]
I'm afraid that even cases look similar, they are 
different :( ideally we need to find a root cause, but for that we need a reproducible example.

Still perhaps @ankur22 knows if we can apply any simple fix here

**Comment by ankur22** [comment]
Hi @yevk,

Thank you for your help in fixing a couple of issues 🙇 I've started to take a look at this issue, and I think i know what the problem is. However i can't replicate it locally, any chance you can provide a minimal script that reproduces this issue?

**Comment by ankur22** [comment]
I've taken another look at this. In Playwright they perform the following:

```js
this._page.mainFrame()._utilityContext().then(utility => utility.evaluate(() => ({ width: innerWidth, height: innerHeight }))),
```

whereas in k6 browser we do:

```go
	var layoutViewport *cdppage.LayoutViewport
	getLayoutMetrics := cdppage.GetLayoutMetrics()
	if _, _, _, layoutViewport, _, _, err = getLayoutMetrics.Do(cdp.WithExecutor(h.ctx, h.session)); err != nil {
		return nil, fmt.Errorf("getting page layout metrics %T: %w", getLayoutMetrics, err)
	}
```

The NPD seemed to occur on the following line:

```go
return filterQuads(layoutViewport.ClientWidth, layoutViewport.ClientHeight, quads)
```

This would mean that `layoutViewport` is `nil`.

I found this [Playwright PR](https://github.com/microsoft/playwright/pull/2669) which hints to an issue when the `innerWidth` changes due it be calculating it in the main context. If we make a switch to working with the utility context like Playwright have done then we may stop seeing these NPDs.

**Comment by ankur22** [comment]
Latest stack trace:

```
go.k6.io/k6/internal/js/modules/k6/browser/common.(*ElementHandle).clickablePoint(0xc0d8269680)
go.k6.io/k6/internal/js/modules/k6/browser/common/element_handle.go:170 +0x2b6
go.k6.io/k6/internal/js/modules/k6/browser/common.(*ElementHandle).newPointerAction.func1({0x2183798, 0xc0ac4cfb90}, 0x0?)
go.k6.io/k6/internal/js/modules/k6/browser/common/element_handle.go:1597 +0x438
go.k6.io/k6/internal/js/modules/k6/browser/common.retryPointerAction({0x2183798, 0xc0ac4cfb90}, 0xc15e61be40, 0xc137ec2f60)
go.k6.io/k6/internal/js/modules/k6/browser/common/element_handle.go:1650 +0x3c
go.k6.io/k6/internal/js/modules/k6/browser/common.(*ElementHandle).newPointerAction.func2({0x2183798, 0xc0ac4cfb90}, 0xc1810fea10, 0xc1810fea80)
go.k6.io/k6/internal/js/modules/k6/browser/common/element_handle.go:1632 +0x53
go.k6.io/k6/internal/js/modules/k6/browser/common.(*Frame).click.(*Frame).newPointerAction.func2({0x2183798, 0xc0ac4cfb90}, 0xc1810fea10, 0xc1810fea80)
go.k6.io/k6/internal/js/modules/k6/browser/common/frame.go:2054 +0x114
created by go.k6.io/k6/internal/js/modules/k6/browser/common.call in goroutine 7800067
go.k6.io/k6/internal/js/modules/k6/browser/common/helpers.go:104 +0x14c
```
