### ISSUE TITLE
nil pointer: page.getFrameElement

### ISSUE THREAD

**Issue by inancgumus** [grafana/k6#4124]
### Brief summary

Test Run ID: 2015119

There is a nil pointer exception in:

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x11af156]

goroutine 2213 [running]:
github.com/grafana/xk6-browser/common.(*Page).getFrameElement(0xc00225d1e0, 0xc002d50540)
github.com/grafana/xk6-browser@v1.1.0/common/page.go:274 +0x2d6
github.com/grafana/xk6-browser/common.(*Frame).FrameElement(0xc002d50540)
github.com/grafana/xk6-browser@v1.1.0/common/frame.go:834 +0x106
github.com/grafana/xk6-browser/common.(*ElementHandle).checkHitTargetAt(0xc0002d1a90, {0x19d8f28?, 0xc002a7ab60?}, {0x407eff2000000000, 0x407da00000000000})
github.com/grafana/xk6-browser@v1.1.0/common/element_handle.go:70 +0x6a
github.com/grafana/xk6-browser/common.(*ElementHandle).newPointerAction.func1({0x19d8f28, 0xc002a7ab60}, 0x0?)
github.com/grafana/xk6-browser@v1.1.0/common/element_handle.go:1449 +0x52b
github.com/grafana/xk6-browser/common.retryPointerAction({0x19d8f28, 0xc002a7ab60}, 0xc000ea60a0, 0xc000b3cf00)
github.com/grafana/xk6-browser@v1.1.0/common/element_handle.go:1488 +0x3c
github.com/grafana/xk6-browser/common.(*ElementHandle).newPointerAction.func2({0x19d8f28?, 0xc002a7ab60?}, 0xc000b3cf00?, 0x44f120?)
github.com/grafana/xk6-browser@v1.1.0/common/element_handle.go:1476 +0x35
github.com/grafana/xk6-browser/common.(*Frame).click.(*Frame).newPointerAction.func2({0x19d8f28, 0xc002a7ab60}, 0xc0009d3e00, 0xc0009d3e60)
github.com/grafana/xk6-browser@v1.1.0/common/frame.go:1991 +0x116
created by github.com/grafana/xk6-browser/common.call in goroutine 2212
github.com/grafana/xk6-browser@v1.1.0/common/helpers.go:102 +0x15c
```

### xk6-browser version

1.1.0

### OS

remote

### Chrome version

remote

### Steps to reproduce the problem

Run the test script locally.

### Expected behaviour

No panics.

### Actual behaviour

Panics.

**Comment by ankur22** [comment]
After taking a close look at this issue, as well as taking inspiration from Playwright code base (specifically [1](https://github.com/microsoft/playwright/blob/63329a34712d7afd89c654097b1403065e1d4f13/packages/playwright-core/src/server/chromium/crPage.ts#L1124) -> [2](https://github.com/microsoft/playwright/blob/1afb56ee1b63ffbb972a1773432979b865878072/packages/playwright-core/src/server/chromium/crPage.ts#L392) -> [3](https://github.com/microsoft/playwright/blob/1afb56ee1b63ffbb972a1773432979b865878072/packages/playwright-core/src/server/chromium/crPage.ts#L1188)) and this Playwright [issue](https://github.com/microsoft/playwright/issues/2974), i think if your seeing this error then you're very likely hitting a race condition during an API call to `click` on an element, and the:

1. Page has navigated away;
2. Or the element that your clicking on is now missing;
3. Or you're working directly with `elementHandle` instead of `locators`.

If you're seeing this error while working with `locators` then please update to the latest version of k6 (`v0.56.0` as of writing this) where we have fixed an issue with locators panicking during navigations ([PR](https://github.com/grafana/xk6-browser/pull/1534)).

**Comment by ankur22** [comment]
I haven't seen this error again for a while, so i'm closing this issue.
