### ISSUE TITLE
isVisible sometimes times out

### ISSUE THREAD

**Issue by inancgumus** [grafana/k6#4365]
### Brief summary

While testing locally with the script below, among 142 "checks", 4 of them fails with the following error:

```
ERRO[0081] Uncaught (in promise) GoError: checking is "//p[text()=\"National Park Foundation Explorascope\"]" visible: timed out after 30s
running at github.com/grafana/xk6-browser/api.Locator.IsVisible-fm (native)
browser at cart item name (file:///Users/inanc/grafana/k6browser/tests/issue986.js:36:32(6))
        at go.k6.io/k6/js/modules/k6.(*K6).Check-fm (native)
        at file:///Users/inanc/grafana/k6browser/tests/issue986.js:35:10(53)  executor=per-vu-iterations scenario=browser
```

The root cause seems to be related to grafana/xk6-browser#981, but it could be something else. A suggestion from @ankur22 can reveal the root cause: _"Maybe we need a screenshot of the page before the check to debug what's going on. grafana/xk6-browser#981 is really all about not waiting for the element at all, whereas this feels like a new issue."._

### xk6-browser version

v1.0.0

### OS

macOS Ventura 13.1

### Chrome version

114.0.5735.133 (Official Build) (arm64)

### Steps to reproduce the problem

<details><summary>Run this script.</summary>

```js
import { check } from 'k6';
import { browser } from 'k6/x/browser';

export const options = {
  scenarios: {
    browser: {
      executor: 'per-vu-iterations',
      maxDuration: '5m',
      vus: 5,
      iterations: 10,
      options: {
        browser: {
          type: 'chromium',
        },
      },
    },
  }
}

export default async function () {
  const page = browser.newPage();

  try {
    // User journy in SPA application
    await page.goto('otel demo app'); // TODO: change it to the otel app URL

    const productCard = page.locator('(//div[@data-cy="product-card"])[1]')
    await productCard.click()

    const quantityOption = page.locator('[data-cy="product-quantity"]')
    quantityOption.selectOption('3')
    const addToCardBtn = page.locator('[data-cy="product-add-to-cart"]')
    await addToCardBtn.click();
    
    check(page, {
      'cart item name': page => page.locator('//p[text()="National Park Foundation Explorascope"]').isVisible() === true,
      'cart item quantity': page => page.locator('//p[text()="3"]').isVisible() === true
    })

    // Check GH link to force another navigation
    await Promise.all([
      page.waitForNavigation(),
      page.locator('footer a').click(),
    ]);
    check(page, {
      'gh-author': page.locator(
        'div#repository-container-header span.author a'
      ).textContent().includes('open-telemetry'),
    });
  } finally {
    page.close();
  }
}
```

</details>

### Expected behaviour

All checks pass if the website is determined to be displaying the cart element (`"//p[text()=\"National Park Foundation Explorascope\"]"`) in all test runs.

### Actual behaviour

Checks sometimes fail.

**Comment by AgnesToulet** [comment]
Closing because the issue is too old.
