### ISSUE TITLE
"launching browser: browser process ended unexpectedly"

### ISSUE THREAD

**Issue by tmc** [grafana/k6#4370]
### Brief summary

I get this error with no more detail when running with debug: true and/or --verbose:

```
ERRO[0000] process with PID 55973 unexpectedly ended: exit status 126  category=browser elapsed="0 ms" goroutine=100
ERRO[0000] Uncaught (in promise) GoError: launching browser: browser process ended unexpectedly
	at github.com/grafana/xk6-browser/browser.mapBrowserType.func2 (native)
	at file:///Users/tmc/xxx/basic-web-interaction.js:10:36(7)  executor=shared-iterations scenario=default
```

I'd expect more detail here as I don't really know what to do to debug.

### xk6-browser version

k6 v0.44.1

### OS

macos 13.3.1

### Chrome version

114.0.5735.90

### Steps to reproduce the problem

import { chromium } from 'k6/experimental/browser';

export default async function () {
  const browser = chromium.launch({
    headless: false,
    timeout: '60s', // Or whatever time you want to define
  });
  const page = browser.newPage();

  try {
    await page.goto('https://test.k6.io/');
    page.screenshot({ path: 'screenshot.png' });
  } finally {
    page.close();
    browser.close();
  }
}

### Expected behaviour

It works.

### Actual behaviour

ERRO[0000] process with PID 55973 unexpectedly ended: exit status 126  category=browser elapsed="0 ms" goroutine=100
ERRO[0000] Uncaught (in promise) GoError: launching browser: browser process ended unexpectedly
	at github.com/grafana/xk6-browser/browser.mapBrowserType.func2 (native)
	at file:///Users/tmc/xxx/basic-web-interaction.js:10:36(7)  executor=shared-iterations scenario=default

**Comment by bhadmus** [comment]
This is still open? Does that mean that there isn't a solution yet? I have the same issue with the sample script that k6 provided, I got this error when I executed the template script with `k6 run browser-script.js`

I didn't experience this on my Intel Chip Mac or Windows system, I am only experiencing this on the M1 Chip

```


         /\      Grafana   /‾‾/  
    /\  /  \     |\  __   /  /   
   /  \/    \    | |/ /  /   ‾‾\ 
  /          \   |   (  |  (‾)  |
 / __________ \  |_|\_\  \_____/ 

     execution: local
        script: browser-script.js
        output: -

     scenarios: (100.00%) 1 scenario, 1 max VUs, 10m30s max duration (incl. graceful stop):
              * ui: 1 iterations shared among 1 VUs (maxDuration: 10m0s, gracefulStop: 30s)

ERRO[0000] process with PID 6755 unexpectedly ended: exit status 126  category=browser elapsed="0 ms" source=browser


  █ TOTAL RESULTS 

    HTTP
    http_req_duration..............: avg=243.63ms min=243.63ms med=243.63ms max=243.63ms p(90)=243.63ms p(95)=243.63ms
      { expected_response:true }...: avg=243.63ms min=243.63ms med=243.63ms max=243.63ms p(90)=243.63ms p(95)=243.63ms
    http_req_failed................: 0.00%  0 out of 1
    http_reqs......................: 1      1.543177/s

    EXECUTION
    iteration_duration.............: avg=438.87µs min=438.87µs med=438.87µs max=438.87µs p(90)=438.87µs p(95)=438.87µs
    iterations.....................: 1      1.543177/s

    NETWORK
    data_received..................: 7.2 kB 11 kB/s
    data_sent......................: 1.8 kB 2.8 kB/s




running (00m00.7s), 0/1 VUs, 0 complete and 1 interrupted iterations
ui   ✗ [======================================] 1 VUs  00m00.0s/10m0s  1/1 shared iters
ERRO[0000] error building browser on IterStart: launching browser: browser process ended unexpectedly at default (file:///Users/sanguine/Tutorial/performance-tests/k6/rusty-practice/browser-script.js:30:16(0)) 
```

See template script

```
import http from "k6/http";
import exec from 'k6/execution';
import { browser } from "k6/browser";
import { sleep, check, fail } from 'k6';

const BASE_URL = __ENV.BASE_URL || "https://quickpizza.grafana.com";

export const options = {
  scenarios: {
    ui: {
      executor: "shared-iterations",
      vus: 1,
      iterations: 1,
      options: {
        browser: {
          type: "chromium",
        },
      },
    },
  },
};

export function setup() {
  let res = http.get(BASE_URL);
  if (res.status !== 200) {
    exec.test.abort(`Got unexpected status code ${res.status} when trying to setup. Exiting.`);
  }
}

export default async function() {
  let checkData;
  const page = await browser.newPage();

  try {
    await page.goto(BASE_URL);

    checkData = await page.locator("h1").textContent();
    check(page, {
      header: checkData === "Looking to break out of your pizza routine?",
    });

    await page.locator('//button[. = "Pizza, Please!"]').click();
    await page.waitForTimeout(500);

    await page.screenshot({ path: "screenshot.png" });

    checkData = await page.locator("div#recommendations").textContent();
    check(page, {
      recommendation: checkData !== "",
    });
  } catch (error) {
    fail(`Browser iteration failed: ${error.message}`);
  } finally {
    await page.close();
  }

  sleep(1);
}

```

**Comment by AgnesToulet** [comment]
Hi! Can you try running the test with `K6_BROWSER_HEADLESS=false` and `K6_BROWSER_DEBUG=true`, this may help finding out 1. if the browser even started and 2. when the browser ended.

I wonder if this could be a config issue that prevents the test to open any browser. Do you have a Chromium-based browser installed on your machine?

**Comment by bhadmus** [comment]
> Hi! Can you try running the test with `K6_BROWSER_HEADLESS=false` and `K6_BROWSER_DEBUG=true`, this may help finding out 1. if the browser even started and 2. when the browser ended.
> 
> I wonder if this could be a config issue that prevents the test to open any browser. Do you have a Chromium-based browser installed on your machine?

I did as instructed and this is what I got.

```
K6_BROWSER_HEADLESS=false K6_BROWSER_DEBUG=true k6 run browser-script.js

         /\      Grafana   /‾‾/  
    /\  /  \     |\  __   /  /   
   /  \/    \    | |/ /  /   ‾‾\ 
  /          \   |   (  |  (‾)  |
 / __________ \  |_|\_\  \_____/ 

     execution: local
        script: browser-script.js
        output: -

     scenarios: (100.00%) 1 scenario, 1 max VUs, 10m30s max duration (incl. graceful stop):
              * ui: 1 iterations shared among 1 VUs (maxDuration: 10m0s, gracefulStop: 30s)

ERRO[0000] process with PID 19207 unexpectedly ended: exit status 126  category=browser elapsed="0 ms" iteration_id=cbc936d361f5f1b1 source=browser
DEBU[0000] Metrics emission of VUs and VUsMax metrics stopped 
DEBU[0000] Executor finished successfully                executor=ui startTime=0s type=shared-iterations
DEBU[0000] teardown() is not defined or not exported, skipping! 
DEBU[0000] The test run was interrupted, returning 'error building browser on IterStart: launching browser: browser process ended unexpectedly at default (file:///Users/sanguine/Tutorial/performance-tests/k6/rusty-practice/browser-script.js:30:16(0))' instead of '%!s(<nil>)'  phase=execution-scheduler-run
DEBU[0000] Test finished with an error                   error="error building browser on IterStart: launching browser: browser process ended unexpectedly at default (file:///Users/sanguine/Tutorial/performance-tests/k6/rusty-practice/browser-script.js:30:16(0))"
DEBU[0000] Stopping vus and vux_max metrics emission...  phase=execution-scheduler-init
DEBU[0000] Releasing signal trap...                     
DEBU[0000] Sending usage report...                      
DEBU[0000] Waiting for metrics and traces processing to finish... 
DEBU[0000] Metrics and traces processing finished!      
DEBU[0000] Stopping outputs...                          
DEBU[0000] Stopping 3 outputs...                         component=output-manager
DEBU[0000] Stopping...                                   component=metrics-engine-ingester
DEBU[0000] Stopped!                                      component=metrics-engine-ingester
DEBU[0000] Generating the end-of-test summary...        
DEBU[0000] Created event subscription                    events="[Exit]" subscriptionID=4
DEBU[0000] Created event subscription                    events="[IterStart IterEnd]" subscriptionID=1


  █ TOTAL RESULTS 

    HTTP
    http_req_duration..............: avg=117.8ms  min=117.8ms  med=117.8ms  max=117.8ms  p(90)=117.8ms  p(95)=117.8ms 
      { expected_response:true }...: avg=117.8ms  min=117.8ms  med=117.8ms  max=117.8ms  p(90)=117.8ms  p(95)=117.8ms 
    http_req_failed................: 0.00%  0 out of 1
    http_reqs......................: 1      2.334011/s

    EXECUTION
    iteration_duration.............: avg=777.62µs min=777.62µs med=777.62µs max=777.62µs p(90)=777.62µs p(95)=777.62µs
    iterations.....................: 1      2.334011/s

    NETWORK
    data_received..................: 7.2 kB 17 kB/s
    data_sent......................: 1.8 kB 4.2 kB/s




running (00m00.4s), 0/1 VUs, 0 complete and 1 interrupted iterations
ui   ✗ [======================================] 1 VUs  00m00.0s/10m0s  1/1 shared iters
DEBU[0000] Usage report sent successfully               
DEBU[0000] Removed event subscription                    subscriptionID=1
DEBU[0000] Removed event subscription                    subscriptionID=1
DEBU[0000] Removed event subscription                    subscriptionID=3
DEBU[0000] Removed all event subscriptions               subscriptions=3
DEBU[0000] Everything has finished, exiting k6 with an error!  error="error building browser on IterStart: launching browser: browser process ended unexpectedly at default (file:///Users/sanguine/Tutorial/performance-tests/k6/rusty-practice/browser-script.js:30:16(0))"
DEBU[0000] Removed event subscription                    subscriptionID=1
ERRO[0000] error building browser on IterStart: launching browser: browser process ended unexpectedly at default (file:///Users/sanguine/Tutorial/performance-tests/k6/rusty-practice/browser-script.js:30:16(0)) 
DEBU[0000] Re%                                  
```

**Comment by AgnesToulet** [comment]
I'll check if there is a way to get more information on the Chrome process but it seems like the browser didn't even start. Can you confirm you have a Chromium-based browser installed and working on your machine? 

If so, you could try this to see if it generates a crash report: https://support.google.com/chrome/a/answer/14286882?hl=en

**Comment by bhadmus** [comment]
> I'll check if there is a way to get more information on the Chrome process but it seems like the browser didn't even start. Can you confirm you have a Chromium-based browser installed and working on your machine?
> 
> If so, you could try this to see if it generates a crash report: https://support.google.com/chrome/a/answer/14286882?hl=en

I do not have an admin account, it didn't accept my email. 😏

**Comment by AgnesToulet** [comment]
OK, then can you try to run Chrome on the machine? The command ran by k6 to do that is:
```
<path to Chrome - in my case on Linux, it's '/usr/bin/google-chrome'> --no-default-browser-check --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --disable-dev-shm-usage --no-service-autorun --user-data-dir=/tmp/k6browser-data-3966227371 --disable-breakpad --metrics-recording-only --window-size=800,600 --enable-features=NetworkService,NetworkServiceInProcess --disable-backgrounding-occluded-windows --disable-default-apps --disable-ipc-flooding-protection --disable-renderer-backgrounding --headless --hide-scrollbars --disable-background-timer-throttling --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame --disable-popup-blocking --no-first-run --enable-automation --mute-audio --disable-background-networking --disable-extensions --use-mock-keychain --disable-component-extensions-with-background-pages --disable-hang-monitor --disable-prompt-on-repost --force-color-profile=srgb --password-store=basic --no-startup-window --remote-debugging-port=0
```
