### ISSUE TITLE
Error handling navigation (nil `Frame`)

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [grafana/k6#4411]
### Brief summary

I want to click a button in the browser, the page doesn't even open fully.

### xk6-browser version

k6 v0.40.0 ((devel), go1.19, darwin/arm64)

### OS

macOS 12.6 (21G115)

### Chrome version

106.0.5249.119

### Steps to reproduce the problem

```js
const browser = chromium.launch({
  headless: false, // make false for debugging
  slowMo: "500ms",
});
const context = browser.newContext();
const page = context.newPage();
page.goto(url, {
  waitUntil: "networkidle",
});
```

### Expected behaviour

browser should not crash

### Actual behaviour

browser crashes with the error:

```
WARN[0012] url:[REDACTED] method:POST err:fetching response body: No resource with given identifier found (-32000)  category="Response:bodySize:fetchBody" elapsed="0 ms" goroutine=376
WARN[0012] url:[REDACTED].js method:GET err:fetching response body: No resource with given identifier found (-32000)  category="Response:bodySize:fetchBody" elapsed="0 ms" goroutine=376
WARN[0012] url:[REDACTED].js method:GET err:fetching response body: No resource with given identifier found (-32000)  category="Response:bodySize:fetchBody" elapsed="0 ms" goroutine=376
INFO[0012] "[REDACTED]"  source=browser-console-api
panic: handling frameNavigated event to "about:blank": we either navigate top level or have old version of the navigated frame
running (00m12.4s), 1/1 VUs, 0 complete and 0 interrupted iterations
goroutine 383 [running]:-------------------------] 1 VUs  00m12.4s/10m0s  0/1 iters, 1 per VU
go.k6.io/k6/js/common.Throw(0x14000f409d0?, {0x1053f8ce0?, 0x14000e0c120?})
        go.k6.io/k6@v0.40.0/js/common/util.go:20 +0x58
github.com/grafana/xk6-browser/k6ext.Panic({0x105407a28, 0x14000886ab0}, {0x104e3690b, 0x27}, {0x1400042dde8, 0x2, 0x2})
        github.com/grafana/xk6-browser@v0.5.0/k6ext/panic.go:51 +0x278
github.com/grafana/xk6-browser/common.(*FrameSession).onFrameNavigated(0x140009b46e0, 0x14000e60b40, 0x20?)
        github.com/grafana/xk6-browser@v0.5.0/common/frame_session.go:650 +0x214
github.com/grafana/xk6-browser/common.(*FrameSession).initEvents.func1()
        github.com/grafana/xk6-browser@v0.5.0/common/frame_session.go:257 +0x650
created by github.com/grafana/xk6-browser/common.(*FrameSession).initEvents
        github.com/grafana/xk6-browser@v0.5.0/common/frame_session.go:228 +0x188
```

**Comment by ankur22** [comment]
I'm closing this since we didn't get user feedback since it was opened.
