### ISSUE TITLE
`*page.FrameTree` is sometimes nil on Windows

### ISSUE THREAD

**Issue by imiric** [grafana/k6#4497]
On Windows we sometimes get back a nil `*page.FrameTree` here:
https://github.com/grafana/xk6-browser/blob/5d95a9e1242eee7dfb174f8bd312c6944d24df64/common/frame_session.go#L228-L233

Happens intermittently in tests, see https://github.com/grafana/xk6-browser/runs/4036384507.

```
=== RUN   TestPageEmulateMedia/Page.emulateMedia/should_work
(*page.FrameTree)(<nil>)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1ee8651]

goroutine 5580 [running]:
github.com/grafana/xk6-browser/common.(*FrameSession).handleFrameTree(0xc000a9c080, 0x0)
	D:/a/xk6-browser/xk6-browser/common/frame_session.go:374 +0xf1
github.com/grafana/xk6-browser/common.(*FrameSession).initFrameTree(0xc000a9c080, 0xc00056e240, 0xc000441f00)
	D:/a/xk6-browser/xk6-browser/common/frame_session.go:237 +0x51e
github.com/grafana/xk6-browser/common.NewFrameSession(0x29e3c00, 0xc00056e240, 0xc000441f00, 0xc000dd8120, 0x0, 0xc000041980, 0x20, 0x29e3c00, 0xc00056e240, 0x0)
	D:/a/xk6-browser/xk6-browser/common/frame_session.go:109 +0x3f0
github.com/grafana/xk6-browser/common.NewPage(0x29e3c00, 0xc00056e240, 0xc000441f00, 0xc000a50640, 0xc000041980, 0x20, 0x0, 0xc000530a01, 0xc000530a20, 0x1298f29, ...)
	D:/a/xk6-browser/xk6-browser/common/page.go:111 +0x830
github.com/grafana/xk6-browser/common.(*Browser).onAttachedToTarget(0xc0001b84b0, 0xc000f60640)
	D:/a/xk6-browser/xk6-browser/common/browser.go:231 +0xafc
created by github.com/grafana/xk6-browser/common.(*Browser).initEvents.func1
	D:/a/xk6-browser/xk6-browser/common/browser.go:165 +0x2a5
FAIL	github.com/grafana/xk6-browser/tests	18.893s
?   	github.com/grafana/xk6-browser/testutils	[no test files]
?   	github.com/grafana/xk6-browser/testutils/browsertest	[no test files]
FAIL
```

**Comment by AgnesToulet** [comment]
Closing this because we haven't seen this in tests for a while now.
